# Generated by Django 2.2.7 on 2020-01-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('year_of_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('year_of_birth', models.IntegerField()),
                ('lending_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('genre', models.CharField(choices=[('a', 'Adventure'), ('b', 'Biography'), ('c', 'Crime'), ('f', 'Fiction')], max_length=1, null=True)),
                ('release_date', models.DateField()),
                ('plot', models.TextField()),
                ('pages', models.PositiveIntegerField(help_text='without Table of Contents')),
                ('e_book', models.BooleanField()),
                ('authors', models.ManyToManyField(blank=True, to='yalib.Author')),
                ('lender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yalib.Lender')),
                ('library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yalib.Library')),
            ],
        ),
    ]
