# Generated by Django 2.2.7 on 2020-01-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yalib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='lender',
        ),
    ]
