# Generated by Django 2.2.7 on 2020-01-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yalib', '0002_remove_book_lender'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yalib.Book'),
        ),
    ]
