# Generated by Django 2.2.7 on 2020-01-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yalib', '0003_lender_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lender',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='lender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yalib.Lender'),
        ),
    ]
